# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'CommonProject' do
pod 'Moya', '~> 8.0.5'
pod 'Moya/RxSwift', '~> 8.0.5'
pod 'RxSwift',    '~> 3.6.1'
pod 'RxCocoa',    '~> 3.6.1'
pod 'Kingfisher', '~> 3.10.4'
pod 'RxDataSources', '~> 1.0.4'
pod 'ObjectMapper', '~> 2.2.8'
pod 'IQKeyboardManagerSwift', '~> 4.0.11'
pod 'SnapKit', '~> 3.2.0'
pod 'EZSwiftExtensions', '~> 1.11'
pod 'ESTabBarController-swift', '~> 2.5'
#pod 'Moya-ObjectMapper/RxSwift'
#pod 'SwiftPullToRefresh', '~> 1.1.0'
#pod 'MBProgressHUD'
#pod 'PKHUD', '~> 4.0'
#pod 'UMengAnalytics-NO-IDFA'
#pod 'UMengUShare/UI'
#pod 'UMengUShare/Social/ReducedWeChat'
#pod ‘UMengUShare/Social/WeChat'


  target 'CommonProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CommonProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
